### ISSUE TITLE
feature: add Message::Redeem

### ISSUE THREAD

**Issue by vesdev** [jprochazk/tmi-rs#3]
parse the custom-reward-id tag.

could expose this in something like ``msg.reward_id()``,
but having ``Message::Redeem/Message::Reward ``similar to tmi.js ``client.on('redeem') `` probably makes more sense

**Comment by jprochazk** [comment]
Let's keep it as an optional field on `Privmsg`. You can't handle arbitrary redeems through IRC, and I wouldn't want to give any users the impression that `tmi-rs` can somehow do that.

All these places need to be updated:
- add the tag to https://github.com/jprochazk/tmi-rs/blob/5eaa0c3f699de009f49e05ae771e0f9a8e63f6ed/src/irc.rs#L664
- add it as an optional field on `Privmsg` https://github.com/jprochazk/tmi-rs/blob/5eaa0c3f699de009f49e05ae771e0f9a8e63f6ed/src/msg/privmsg.rs#L14
- parse the field https://github.com/jprochazk/tmi-rs/blob/5eaa0c3f699de009f49e05ae771e0f9a8e63f6ed/src/msg/privmsg.rs#L144
- add a getter for it https://github.com/jprochazk/tmi-rs/blob/5eaa0c3f699de009f49e05ae771e0f9a8e63f6ed/src/msg/privmsg.rs#L85
- add a test, ideally from a real message https://github.com/jprochazk/tmi-rs/blob/5eaa0c3f699de009f49e05ae771e0f9a8e63f6ed/src/msg/privmsg.rs#L209
